// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSource(arg1) {
  return window['go']['main']['App']['AddSource'](arg1);
}

export function BackupDatabase() {
  return window['go']['main']['App']['BackupDatabase']();
}

export function DeleteAsset(arg1) {
  return window['go']['main']['App']['DeleteAsset'](arg1);
}

export function DeleteHistory(arg1) {
  return window['go']['main']['App']['DeleteHistory'](arg1);
}

export function DeleteRebalance(arg1) {
  return window['go']['main']['App']['DeleteRebalance'](arg1);
}

export function DeleteSource(arg1) {
  return window['go']['main']['App']['DeleteSource'](arg1);
}

export function GetAllIndexes() {
  return window['go']['main']['App']['GetAllIndexes']();
}

export function GetAssets() {
  return window['go']['main']['App']['GetAssets']();
}

export function GetDBInfo() {
  return window['go']['main']['App']['GetDBInfo']();
}

export function GetFundInfo(arg1) {
  return window['go']['main']['App']['GetFundInfo'](arg1);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetIndexData(arg1) {
  return window['go']['main']['App']['GetIndexData'](arg1);
}

export function GetLatestRebalance() {
  return window['go']['main']['App']['GetLatestRebalance']();
}

export function GetPortfolioRatio() {
  return window['go']['main']['App']['GetPortfolioRatio']();
}

export function GetRebalanceAdvice(arg1) {
  return window['go']['main']['App']['GetRebalanceAdvice'](arg1);
}

export function GetRebalanceHistory() {
  return window['go']['main']['App']['GetRebalanceHistory']();
}

export function GetSources() {
  return window['go']['main']['App']['GetSources']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function SaveAsset(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveAsset'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveRebalance(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SaveRebalance'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SaveSnapshot() {
  return window['go']['main']['App']['SaveSnapshot']();
}

export function SetPassword(arg1) {
  return window['go']['main']['App']['SetPassword'](arg1);
}

export function UpdateAsset(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateAsset'](arg1, arg2, arg3, arg4);
}

export function UpdateAssetAmount(arg1, arg2) {
  return window['go']['main']['App']['UpdateAssetAmount'](arg1, arg2);
}

export function VerifyPassword(arg1) {
  return window['go']['main']['App']['VerifyPassword'](arg1);
}
