// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSource(arg1:string):Promise<void>;

export function BackupDatabase():Promise<void>;

export function DeleteAsset(arg1:number):Promise<void>;

export function DeleteHistory(arg1:number):Promise<void>;

export function DeleteRebalance(arg1:number):Promise<void>;

export function DeleteSource(arg1:number):Promise<void>;

export function GetAllIndexes():Promise<Array<Record<string, any>>>;

export function GetAssets():Promise<Array<Record<string, any>>>;

export function GetDBInfo():Promise<Record<string, any>>;

export function GetFundInfo(arg1:string):Promise<Record<string, any>>;

export function GetHistory():Promise<Array<Record<string, any>>>;

export function GetIndexData(arg1:string):Promise<Record<string, any>>;

export function GetLatestRebalance():Promise<Record<string, any>>;

export function GetPortfolioRatio():Promise<Record<string, number>>;

export function GetRebalanceAdvice(arg1:number):Promise<Record<string, any>>;

export function GetRebalanceHistory():Promise<Array<Record<string, any>>>;

export function GetSources():Promise<Array<Record<string, any>>>;

export function GetSystemInfo():Promise<Record<string, any>>;

export function IsAuthenticated():Promise<boolean>;

export function IsFirstRun():Promise<boolean>;

export function Logout():Promise<void>;

export function SaveAsset(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<void>;

export function SaveRebalance(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number,arg7:number,arg8:string):Promise<void>;

export function SaveSnapshot():Promise<void>;

export function SetPassword(arg1:string):Promise<void>;

export function UpdateAsset(arg1:number,arg2:string,arg3:string,arg4:number):Promise<void>;

export function UpdateAssetAmount(arg1:number,arg2:number):Promise<void>;

export function VerifyPassword(arg1:string):Promise<boolean>;
